apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrcode-generator
  template:
    metadata:
      labels:
        app: qrcode-generator
    spec:
      containers:
      - name: app
        image: felipecs8/qrcode-generator:v1
        ports:
        - containerPort: 8080