apiVersion: v1
kind: Service
metadata:
  name: conversor-temperatura-service
spec:
  selector:
    app: conversor-temperatura
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
