version: '3'

services:
  app:
    build: .
    container_name: app.qrcode-generator
    ports:
      - "8091:80"
    networks:
      - default
      - interdocker
    restart: unless-stopped

networks:
  default:
    driver: bridge
  interdocker:
    external: true