name: 'Container CI'

on:
  pull_request: # [main]
    branches:
      - main
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - app1/**
  


jobs:

  container:
    name: 'Container'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: .
        shell: bash

    steps:

    - if: github.event_name == 'pull_request'
      name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      if: github.event_name == 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      if: github.event_name == 'pull_request'
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      if: github.event_name == 'pull_request'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/conversao-temperatura:v1
